---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 홈
    url: "/home.html"
  - title: 릴리즈 노트
    url: "/releasenotes.html"
  - title: xCP를 시작하십시오
    type: solutions
    entries:
    - title: xCP에 대해 자세히 알아보십시오
      url: "/index.html"
    - title: xCP NFS 애드온 기능
      url: "/xcp-nfs-add-ons.html"
    - title: 지원되지 않는 기능입니다
      url: "/xcp-unsupported-features.html"
    - title: 지원되는 구성
      url: "/xcp-supported-configurations.html"
    - title: xCP에서 사용하는 포트
      url: "/xcp-ports-used.html"
  - title: xCP를 설치합니다
    entries:
    - title: xCP 설치를 준비합니다
      url: "/xcp-install-xcp.html"
    - title: xCP NFS용 Linux를 준비합니다
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: xCP SMB용 Windows를 준비합니다
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: 파일 분석 준비
      url: "/xcp-prepare-file-analytics.html"
    - title: xCP NFS를 설치합니다
      url: "/xcp-install-xcp-nfs.html"
    - title: xCP SMB를 설치합니다
      url: "/xcp-install-xcp-smb.html"
    - title: File Analytics for NFS를 설치합니다
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: SMB용 File Analytics를 설치합니다
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: xCP를 구성합니다
    entries:
    - title: XCP NFS용 INI 파일을 구성합니다
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: 성능 튜닝
      url: "/xcp-performance-tuning.html"
    - title: 환경 변수
      url: "/xcp-environment-variable.html"
    - title: POSIX 커넥터를 구성합니다
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: HDFS 커넥터를 구성합니다
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: 다중 노드 스케일아웃 구성
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: S3 커넥터를 구성합니다
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: 데이터 마이그레이션 계획
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: NFS 데이터 마이그레이션 계획
      url: "/xcp-plan-nfs-data-migration.html"
    - title: SMB 데이터 마이그레이션 계획
      url: "/xcp-plan-smb-data-migration.html"
    - title: HDFS 데이터 마이그레이션 계획
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: 파일 분석을 사용하여 계획
      url: "/xcp-using-file-analytics.html"
      entries:
      - title: 파일 분석 액세스
        url: "/xcp-access-file-analytics.html"
      - title: 파일 서버를 추가합니다
        url: "/xcp-add-file-servers.html"
      - title: 스캔을 실행합니다
        url: "/xcp-run-a-scan.html"
    - title: 필터
      url: "/xcp-filters.html"
    - title: NFS 및 SMB용 로깅(옵션)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: 데이터 마이그레이션
    entries:
    - title: NFS 데이터 마이그레이션
      entries:
      - title: NFS 데이터를 마이그레이션하는 명령입니다
        url: "/xcp-migrate-nfs-data.html"
    - title: SMB 데이터 마이그레이션
      url: "/xcp-migrate-smb-data.html"
    - title: HDFS 데이터를 마이그레이션합니다
      url: "/xcp-migrate-hdfs-data.html"
    - title: 동일한 호스트에서 여러 xCP 작업을 실행합니다
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: 추가 NFS 기능
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: 문제 해결
    entries:
    - title: xCP NFS 오류 문제 해결
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: xCP SMB 오류 문제 해결
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: xCP File Analytics 오류 문제 해결
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: 자세한 정보를 확인하십시오
    url: "/get-more-information.html"
