---
sidebar: sidebar 
permalink: xcp-migrate-nfs-additional-features.html 
keywords: xcp, nfs, chomod, chown, posix, ownership, change, file, path, directory, command, scan 
summary: xCP에는 NFS 공유 또는 POSIX 경로에 대한 파일 및 디렉토리의 소유권 및 권한을 쉽게 변경할 수 있는 몇 가지 추가 NFS 기능이 포함되어 있습니다. 
---
= 추가 NFS 기능
:allow-uri-read: 


[role="lead"]
xCP에는 몇 가지 추가 NFS 기능이 포함되어 있습니다.



== Chown과 chmod

xCP 'chown' 및 'chmod' 명령을 사용하여 지정된 NFS 공유 또는 POSIX 경로에 대한 모든 파일과 디렉토리를 재귀적으로 변경할 수 있습니다. 이렇게 하면 수백만 파일의 성능이 향상됩니다.


NOTE: 파일의 소유권을 변경하기 전에 새 소유자를 구성해야 합니다. 그렇지 않으면 명령이 실패합니다. xCP의 chown과 chmod 명령은 리눅스의 chown과 chmod 명령어와 비슷하게 동작한다.



=== chmod

chmod 명령은 선택한 디렉토리 구조의 모든 파일에 대한 파일 권한을 검사하고 변경합니다. chmod 명령을 사용하려면 모드 또는 참조와 NFS 공유 또는 POSIX 경로가 변수로 필요합니다. xCP의 chmod는 주어진 경로에 대한 권한을 재귀적으로 변경합니다. "chmod" 명령을 사용하면 스캔한 총 파일과 출력에서 변경된 사용 권한을 표시할 수 있습니다.

* 예: *

....
xcp chmod -mode 777 NFS [server:/export path | file://<NFS mounted path>]
xcp chmod -mode 707 nfs_server01.netapp.com:/export1
xcp chmod -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com: export1
xcp chmod -match “fnm(‘file.txt’)” -mode 111 file:///mnt/nfs_mount_point/
xcp chmod -exclude “fnm(‘file.txt’)” -mode 111 file:///demo/user1/
....
자세한 내용은 xCP help chmod 명령을 실행합니다.



=== 직접

xCP "chown" 명령을 사용하여 지정된 NFS 공유 또는 POSIX 경로에 대한 모든 파일과 디렉토리를 재귀적으로 변경할 수 있습니다. 이렇게 하면 수백만 파일의 성능이 향상됩니다.

chown 명령은 선택한 디렉토리 구조에 있는 모든 파일의 소유권을 검색하고 변경합니다. chown 명령을 사용하려면 NFS 공유 또는 POSIX 경로가 변수로 필요합니다. xCP 'chown'은 주어진 경로에 대한 소유권을 재귀적으로 변경합니다.

* 예 *

....
xcp chown -user user1 NFS [server:/export path | file://<NFS mounted path>
xcp chown -user user1 nfs_server01.netapp.com:/export1
xcp chown -user user1 -group group1 nfs_server01.netapp.com:/export1/dir1/
xcp chown  -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com:/export1
xcp chown -match “fnm(‘file.txt’)” -user user1 file:///mnt/nfs_mount_point/
xcp chown -exclude “fnm(‘file.txt’)” -user user1 -group group1
xcp chown -user-from user1 -user user2 file:///mnt/nfs_mount_point/
xcp chown -group-from group1 -group group2 nfs_server01.netapp.com:/export1/
....
자세한 내용은 xCP 도움말 chown 명령을 실행하십시오.



== xCP 추정

xCP 추정 기능은 기준을 완료하는 데 걸리는 시간을 예측합니다 `copy` 소스에서 대상으로 작업을 수행합니다. 기준선을 완료하는 데 필요한 예상 시간을 계산합니다 `copy` CPU, RAM, 네트워크 또는 기타 매개변수와 같이 현재 사용 가능한 모든 시스템 리소스를 사용하여 작업을 수행합니다. 를 사용할 때 `-target` xCP는 샘플 복사 작업을 실행하여 예상 시간을 찾습니다.

* 예 *

....
server : NFS server IP
export : NFS exported path for the above IP

xcp static estimation
xcp estimate -id <scan id>

xcp live estimation with default time
xcp estimate -id <scan id> -target server:/export

xcp live estimation with -t option
xcp estimate -id <scan id> -t <time for which estimation should run> -target server:/export
....