---
sidebar: sidebar 
permalink: xcp-nfs-add-ons.html 
keywords: xcp, nfs, hdfs, connector, configure, security 
summary: XCP NFS 애드온 기능은 POSIX 및 HDFS 커넥터 사용을 지원하고, 보안을 강화하고, 스케일아웃 아키텍처를 사용하여 데이터 마이그레이션 속도를 높여줍니다. 
---
= xCP NFS 애드온 기능


[role="lead"]
XCP NFS 애드온 기능은 POSIX 및 HDFS 커넥터 사용을 지원하고, 보안을 강화하고, 스케일아웃 아키텍처를 사용하여 데이터 마이그레이션 속도를 높여줍니다.



== NFSv4 지원

데이터 센터의 소스, 대상 및 카탈로그 볼륨에서 NFSv4만 사용하도록 설정하면 내보내기 경로 대신 POSIX 경로를 사용하여 데이터를 마이그레이션할 수 있습니다. POSIX 경로를 사용하려면 먼저 xCP를 실행하는 호스트 시스템에 소스, 대상 및 카탈로그 볼륨을 마운트한 다음 POSIX 파일 경로를 사용하여 XCP에 소스 및 대상을 제공해야 합니다. 을 참조하십시오 link:xcp-configure-posix-connector-nfs.html["POSIX 커넥터를 구성합니다"].

[NOTE]
====
* NFSv4 지원은 POSIX 경로로 제한되고 "복사" 작업으로 제한되며, '동기화' 작업은 지원되지 않습니다.
* POSIX 커넥터는 XCP NFSv3 TCP 소켓 클라이언트 엔진에 비해 느릴 수 있습니다.


====


== POSIX 커넥터

xCP 1.8은 POSIX 커넥터를 사용하여 데이터 마이그레이션을 위한 소스, 대상 및 카탈로그 경로를 제공합니다. POSIX 커넥터(파일://)를 통해 XCP는 NFSv4, XFS 및 Veritas와 같은 Linux 마운트 파일 시스템에 액세스할 수 있습니다. 루트가 아닌 사용자의 경우 시스템 관리자는 파일 시스템을 마운트하여 루트가 아닌 사용자에게 파일://접두사가 있는 POSIX 커넥터를 사용하여 파일 시스템에 액세스할 수 있는 기능을 제공할 수 있습니다.

파일을 마운트할 권한이 없거나 데이터 센터에서 사용할 수 있는 지원이 NFSv4로 제한되는 경우 POSIX 커넥터를 사용하면 도움이 됩니다. 이 경우 루트 사용자는 소스 및 대상을 마운트한 다음 POSIX 커넥터를 사용하여 경로에 액세스할 수 있습니다. POSIX 커넥터를 사용하는 경우 'xCP 복사' 작업만 실행할 수 있습니다.



== xCP 보안

xCP 보안 기능을 사용하면 Linux 호스트 시스템에서 루트 이외의 사용자로 마이그레이션을 수행할 수 있습니다. 이전 xCP 버전에서는 Linux 시스템의 루트 사용자로 소스, 대상 및 카탈로그 볼륨에 대한 모든 권한으로 마이그레이션을 수행하고 XCP 작업을 통해 마운트를 완료합니다.

데이터 마이그레이션을 미리 구성할 때는 일반적으로 보안을 끄고 관리자가 가능한 빨리 모든 데이터를 복사하도록 합니다. xCP가 몇 년 동안 사용 중인 운영 환경에서 지속적으로 전환하는 경우 관리자(또는 루트)로 실행하는 것이 안전하지 않습니다. 따라서 루트 사용자로 XCP를 실행해야 하는 요구 사항을 제거하면 보안 환경에서 XCP를 사용할 수 있습니다. 일반 비루트 사용자가 XCP 작업을 실행하면 비루트 사용자는 사용자와 동일한 액세스 권한 및 제한을 갖게 됩니다.

이 보안 환경에서는 루트 사용자가 호스트 시스템에 소스, 대상 및 카탈로그 볼륨을 마운트하고 루트 이외의 사용자가 데이터를 쓸 수 있도록 대상 및 카탈로그 볼륨에 필요한 권한을 제공할 수 있습니다. 이 기능을 사용하면 루트 이외의 사용자가 XCP POSIX 커넥터 기능을 사용하여 마이그레이션을 수행할 수 있습니다.



== xCP 스케일 아웃

지금까지 XCP를 사용한 데이터 마이그레이션은 RAM과 CPU가 더 높은 단일 호스트로 제한되었습니다. 마이그레이션 속도를 높이기 위해 단일 호스트의 메모리와 코어가 증가했지만 페타바이트 단위의 데이터를 복사하는 데 여전히 많은 시간이 걸릴 수 있습니다. xCP 스케일 아웃 아키텍처를 사용하면 여러 호스트를 사용하여 데이터 마이그레이션을 수행할 수 있습니다. 이 기능을 사용하면 여러 Linux 호스트를 사용하여 워크로드를 분산하고 마이그레이션 시간을 줄일 수 있습니다.

단일 시스템의 성능이 충분하지 않은 모든 환경에서 다중 노드 스케일아웃의 이점을 누릴 수 있습니다. 단일 노드의 성능 제한을 극복하기 위해 단일 'copy'(또는 'sccan-m5') 명령을 사용하여 여러 Linux 시스템이나 Hadoop 클러스터 노드에서 작업자를 실행할 수 있습니다. 현재 xCP 스케일아웃은 '복사' 명령 작업에만 지원됩니다.



== Hadoop 분산 파일 시스템 커넥터

xCP는 HDFS(Hadoop Distributed File System) 파일 시스템에서 NetApp 파일 시스템으로 데이터를 마이그레이션할 수 있도록 지원합니다. 보안이 설정된 Hadoop 환경에서는 Hadoop 클러스터의 루트 이외의 사용자가 NetApp NFSv4 내보내기 파일 시스템으로 마이그레이션을 수행할 수 있습니다. HDFS 커넥터(HDFS://)를 통해 xCP는 다양한 공급업체에서 사용할 수 있는 모든 HDFS 파일 시스템에 액세스할 수 있습니다. 루트가 아닌 사용자는 XCP를 사용하여 HDFS 또는 POSIX 커넥터를 사용하여 마이그레이션을 수행할 수 있습니다.

여러 하이엔드 Linux 시스템을 사용하기 때문에 HDFS 클러스터를 xCP 스케일 아웃 구성에 포함할 수 있습니다. 이렇게 하면 추가 XCP 작업자 노드에 대한 요구 사항이 최소화됩니다. 데이터 마이그레이션의 경우 HDFS 클러스터 노드를 재사용하거나 별도의 호스트를 사용하도록 선택할 수 있습니다.


NOTE: HDFS 커넥터는 MapR 및 Cloudera 클러스터에 대해 검증 및 지원되지만 기준 '복사' 작업만 수행할 수 있습니다.
