---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: 데이터 마이그레이션 
---
= NFS 데이터 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
를 사용하여 마이그레이션을 계획한 후 `show` 및 `scan` 명령을 사용하여 NFS 데이터를 마이그레이션할 수 있습니다.



== 복사

copy 명령은 전체 소스 디렉토리 구조를 검사하여 대상 NFSv3 내보내기로 복사합니다. copy 명령을 사용하려면 소스 경로와 대상 경로가 변수로 있어야 합니다. 스캔 및 복사된 파일, 처리량/속도 및 경과 시간 세부 정보가 복사 작업 종료 시 표시됩니다.

* 예: *

[listing]
----
xcp copy -newid <id> src_server:/src_export dst_server:/dst_export
----
* POSIX 경로 예: *

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
실행 `xcp help copy` 를 참조하십시오.



== 다시 시작

'reSUME' 명령은 카탈로그 인덱스 이름 또는 숫자를 지정하여 이전에 중단된 복사 작업을 다시 시작합니다. 카탈로그 인덱스 이름 또는 이전 복사 작업의 번호는 "<catalog path>:/catalog/index" 디렉토리에 저장됩니다.

* 예: *

[listing]
----
xcp resume [options] -id <id used for copy>
----
실행 `xcp help resume` 를 참조하십시오.



== 동기화

'Sync' 명령어는 Catalog Index 태그 이름 또는 이전 복제 작업의 번호를 사용하여 소스 NFS 디렉토리에 대해 수행된 변경 및 수정 사항을 검사합니다. 소스 증분 변경 사항이 타겟 디렉토리에 복사 및 적용됩니다. 이전 카탈로그 인덱스 번호는 동기화 작업 # 다음에 새 [.underline]#으로 대체됩니다.

* 예: *

[listing]
----
xcp sync [options] -id <id used for copy>
----
실행 `xcp help sync` 를 참조하십시오.



== 확인합니다

카탈로그 인덱스 번호를 사용하지 않고 복제 작업 후 소스와 타겟 디렉토리 간의 전체 바이트 단위 데이터 비교를 수행한다. 명령은 사용 권한을 포함하여 수정 시간 및 기타 파일 또는 디렉토리 속성을 확인합니다. 또한 이 명령은 양쪽 모두에서 파일을 읽고 데이터를 비교합니다.

* 예: *

[listing]
----
xcp verify src_server:/src_export dst_server:/dst_export
----
* POSIX 경로 예: *

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
실행 `xcp help verify` 를 참조하십시오.



== iSync 를 선택합니다

를 클릭합니다 `isync` 명령은 소스와 대상을 비교하고 카탈로그 인덱스를 사용하지 않고 타겟의 차이점을 동기화합니다.

* 예 *

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
을 사용할 수 있습니다 `isync` 를 사용하여 `estimate` 에 걸리는 시간을 예측하는 옵션입니다 `isync` 증분 변경 내용을 동기화하는 명령입니다. 를 클릭합니다 `-id` 매개 변수는 이전 복사 작업의 카탈로그 이름을 지정합니다.


NOTE: 사용된 데이터 세트 크기의 25% 이상을 변경하면 이(가) 사용됩니다 `isync estimate` 명령에 필요한 결과가 표시되지 않을 수 있습니다.

* 예 *

[listing]
----
xcp isync estimate -id <name>
----
실행 `xcp help isync` 를 참조하십시오.
