---
sidebar: sidebar 
permalink: xcp-prepare-linux-for-xcp-nfs.html 
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage, 
summary: xCP NFS용 Linux를 준비합니다 
---
= xCP NFS용 Linux를 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
xCP NFS는 Linux 클라이언트 호스트 시스템을 사용하여 병렬 I/O 스트림을 생성하고 사용 가능한 네트워크 및 스토리지 성능을 완벽하게 사용합니다.

루트 및 루트 이외의 사용자에 대한 설정을 구성한 다음 설정에 따라 두 사용자 중 하나를 선택할 수 있습니다.



== 카탈로그를 구성합니다

xCP는 필요한 권한을 사용하여 NFSv3 액세스 카탈로그 디렉토리 또는 POSIX 경로에 작업 보고서와 메타데이터를 저장합니다.

* 카탈로그 프로비저닝은 1회 사전 설치 작업입니다.
* 약 1GB의 공간은 1,000만 개의 오브젝트(디렉토리 및 파일, 하드 링크)마다 인덱싱됩니다. 다시 시작하거나 동기화할 수 있는 각 복제본과 오프라인 검색 가능한 각 스캔에는 인덱스가 필요합니다.
* 성능을 지원하려면 내보내기 디렉토리가 포함된 애그리게이트에 10개 이상의 디스크 또는 SSD가 필요합니다.



NOTE: xCP 카탈로그는 별도로 저장해야 합니다. 소스 또는 대상 NFS 내보내기 디렉토리에 있지 않아야 합니다. xCP는 메타데이터를 유지 관리합니다. 이 메타데이터는 초기 설정 중에 지정된 카탈로그 위치에 있는 보고서입니다. xCP를 사용하여 작업을 실행하기 전에 보고서를 저장할 위치를 지정하고 업데이트해야 합니다.



== 스토리지를 구성합니다

xCP NFS 전환 및 마이그레이션에는 다음과 같은 소스 및 타겟 스토리지 요구사항이 있습니다.

* 소스 및 타겟 서버에는 NFSv3 또는 NFS v4.0 프로토콜 서비스가 활성화되어 있어야 합니다
+
** NFSv4 ACL 마이그레이션의 경우 대상 서버에서 NFSv4 프로토콜 서비스 및 NFSv4 ACL을 활성화해야 합니다


* 소스 볼륨과 타겟 볼륨을 xCP Linux 클라이언트 호스트에 대한 루트 액세스 권한으로 내보내야 합니다
* NFSv4 ACL 마이그레이션의 경우 NFSv4에서는 ACL 마이그레이션이 필요한 볼륨에 인코딩 언어 UTF-8을 사용해야 합니다.


[NOTE]
====
* 관리자가 소스 볼륨을 실수로 수정하지 않도록 하려면 NFSv3 및 NFSv4 내보내기 디렉토리의 소스 볼륨을 읽기 전용으로 구성해야 합니다.
* ONTAP에서 진단 '-atime-update' 옵션을 사용하여 소스 개체에 대한 atime을 보존할 수 있습니다. 이 기능은 ONTAP에서만 사용할 수 있으며 xCP를 실행하는 동안 소스 객체에 atime을 보존하려는 경우에 유용합니다.
* xCP에서는 '-preserve-atime' 옵션을 사용하여 소스 객체에 대한 atime을 보존할 수 있습니다. 이 옵션은 소스 객체를 액세스하는 모든 명령에 사용할 수 있습니다.


====


== 루트 사용자

Linux 시스템의 루트 사용자에게는 소스, 대상 및 카탈로그 볼륨을 마운트할 수 있는 권한이 있습니다.



== 루트가 아닌 사용자

루트가 아닌 사용자는 마운트된 볼륨에 대해 다음과 같은 권한을 가집니다.

* 소스 볼륨에 대한 읽기 권한 액세스
* 마운트된 대상 볼륨에 대한 읽기/쓰기 권한 액세스
* 카탈로그 볼륨에 대한 읽기/쓰기 권한 액세스

