---
sidebar: sidebar 
permalink: xcp-reference-logging-eventlog.html 
keywords: netapp, xcp, reference, event, logging 
summary: XCP 로깅 
---
= EventLog 옵션을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP는 를 사용하여 활성화할 수 있는 이벤트 메시징을 지원합니다 `eventlog` 의 옵션 `xcpLogConfig.json` JSON 구성 파일.

NFS의 경우 모든 이벤트 메시지가 에 기록됩니다 `xcp_event.log` 파일이 기본 위치에 있습니다 `/opt/NetApp/xFiles/xcp/` 또는 다음 환경 변수를 사용하여 구성된 사용자 지정 위치:

`XCP_CONFIG_DIR`


NOTE: 두 위치를 모두 설정하면 `XCP_LOG_DIR` 사용됩니다.

SMB의 경우 모든 이벤트 메시지가 파일에 기록됩니다 `xcp_event.log` 기본 위치에 있습니다 `C:\NetApp\XCP\`.



== NFS 및 SMB용 이벤트 메시징을 위한 JSON 구성

다음 예에서는 JSON 구성 파일을 통해 NFS 및 SMB에 대한 이벤트 메시징을 지원합니다.

.EventLog 옵션이 활성화된 JSON 구성 파일 예
[listing]
----
{
"eventlog": {
"isEnabled": true,
"level": "INFO"
},
"sanitize": false
}
----
.EventLog 및 기타 옵션이 설정된 JSON 구성 파일 예
[listing]
----
{
"logConfig": {
"level": "INFO",
"maxBytes": 52428800,
"name": "xcp.log"
},
"eventlog": {
"isEnabled": true,
"level": "INFO"
},
"syslog": {
"isEnabled": true,
"level": "info",
"serverIp": "10.101.101.10",
"port": 514
},
"sanitize": false
}
----
다음 표에서는 EventLog 하위 옵션과 해당 설명을 보여 줍니다.

[cols="1,1,1,3"]
|===
| 하위 옵션 | JSON 데이터 유형 | 기본값 | 설명 


| `isEnabled` | 부울 | 거짓 | 이 부울 옵션은 이벤트 메시징을 설정하는 데 사용됩니다. false 로 설정하면 이벤트 메시지가 생성되지 않고 이벤트 로그 파일에 이벤트 로그가 게시되지 않습니다. 


| `level` | 문자열 | 정보 | 이벤트 메시지 심각도 필터 수준입니다. 이벤트 메시징은 심각도가 낮은 5가지 심각도 수준(위험, 오류, 경고, 정보 및 디버그)을 지원합니다 
|===
.NFS 이벤트 로그 메시지의 템플릿입니다
다음 표에서는 템플릿과 NFS 이벤트 로그 메시지의 예를 보여 줍니다.

|===
| 템플릿 | 예 


 a| 
`<Time stamp> - <Severity level> {"Event ID": <ID>, "Event
Category":<category of xcp event log>, "Event Type": <type of event
log>, "ExecutionId": < unique ID for each xcp command execution >,
"Event Source": <host name>, "Description": <XCP event log message>}`
 a| 
`2020-07-14 07:07:07,286 - ERROR {"Event ID": 51, "Event Category":
"Application failure", "Event Type": "No space left on destination
error", " ExecutionId ": 408252316712, "Event Source": "NETAPP-01",
"Description": "Target volume is left with no free space while executing
: copy {}. Please increase the size of target volume
10.101.101.101:/cat_vol"}`

|===
.EventLog 메시지 옵션
EventLog 메시지에 사용할 수 있는 옵션은 다음과 같습니다.

* `Event ID`: 각 이벤트 로그 메시지의 고유 식별자입니다.
* `Event Category`: 이벤트 유형 및 이벤트 로그 메시지의 범주에 대해 설명합니다.
* `Event Type`: 이벤트 메시지를 설명하는 짧은 문자열입니다. 여러 이벤트 유형이 하나의 범주에 속할 수 있습니다.
* `Description`설명 필드에는 XCP에서 생성한 이벤트 로그 메시지가 포함됩니다.
* `ExecutionId`: 실행된 각 XCP 명령에 대한 고유 식별자입니다.

