---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: File Analytics for NFS를 설치하거나 업그레이드합니다 
---
= File Analytics for NFS를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
File Analytics for NFS를 설치하거나 업그레이드합니다.

NFS에 대한 시스템 요구 사항은 를 참조하십시오 link:xcp-install-xcp-nfs.html["xCP NFS를 설치합니다"]. configure.sh 스크립트는 Linux 서버에 사용할 수 있는 HTTPD 및 PostgreSQL의 기본 구성을 설치 및 활성화합니다. 필요에 따라 최신 버전으로 변경하거나 업데이트하고 보안 지침을 준수할 수 있습니다.

.시작하기 전에
* xCP 애플리케이션과 xCP를 동일한 호스트에서 동시에 실행할 수 없습니다. XCP 작업이 실행 중인 경우 구성을 시작하기 전에 작업을 완료합니다.
* Linux 시스템은 Yum 리포지토리 서버 또는 인터넷에 연결되어 있어야 합니다.
* Linux 시스템에 방화벽이 구성되어 있는 경우 xCP, xCP 서비스 및 xCP File Analytics에서 사용하는 서비스를 사용하도록 방화벽 설정을 변경해야 합니다. 자세한 내용은 를 참조하십시오 xref:xcp-ports-used.html[xCP에서 사용하는 포트].


.단계
. xCP 폴더로 이동하여 "./configure.sh" 스크립트를 실행합니다. 이 스크립트는 Linux 시스템을 구성하고 다음 작업을 완료하는 데 3~10분이 소요됩니다.
+
.. PostgreSQL 패키지를 다운로드합니다
.. PostgreSQL 서버를 설치합니다
.. HTTPD를 장착하십시오
.. 열린 SSL을 사용하여 자체 서명된 인증서('erver.key and server.crt')를 만듭니다.
.. XCP File Analytics 데이터베이스를 생성합니다


. xCP 구성 메뉴에서 옵션 1 클라이언트 시스템 구성 을 선택합니다.
. 새로 설치하려면 관리자 및 데이터베이스 사용자의 암호를 업데이트합니다. 업그레이드를 위해 XCP 서비스를 중지하라는 메시지가 표시됩니다. 완료되면 옵션 0을 선택합니다.
. xCP 서비스를 시작합니다. 다음 명령을 사용하여 xCP 서비스가 실행 중인지 확인합니다. service xCP status
. 브라우저에서 File Analytics를 실행합니다. *\https://<ip Linux 주소 > /xCP *.

