---
sidebar: sidebar 
permalink: xcp-prepare-file-analytics.html 
keywords: netapp, xcp, prepare, preparing, preparation, file analytics 
summary: 파일 분석을 사용하여 데이터 마이그레이션을 준비하십시오. 
---
= 파일 분석 준비
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
파일 분석을 사용하여 데이터 마이그레이션을 준비하십시오.

파일 분석에는 다음 두 부분이 있습니다.

* Linux에서 실행 중인 파일 분석 서버
* Windows에서 실행되는 xCP SMB 서비스입니다


File Analytics 설치는 다음과 같은 요구 사항을 따릅니다.

* 지원되는 OS 및 시스템 요구사항은 NFS 및 SMB 설치에 대한 사항과 동일합니다. 데이터베이스는 Linux 상자에 상주하므로 최소 10GB의 여유 공간이 있어야 합니다.
* File Analytics 서버를 설치하는 Linux 시스템은 인터넷 또는 yum 리포지토리에 연결되어 있어야 합니다. 설치 스크립트는 yum 저장소와 대화하여 PostgreSQL, HTTP 및 SSL과 같은 필수 패키지를 다운로드합니다.
* File Analytics GUI는 Linux 시스템과 함께 동일한 시스템에서 실행되는 Linux용 XCP 서비스에서만 호스팅할 수 있습니다.
* SMB 서비스를 실행하려면 다음 단계를 수행하십시오.
+
** Windows 상자가 File Analytics 서버가 실행 중인 Linux 시스템을 ping할 수 있는지 확인합니다.
** 방화벽 내부에 있는 경우 포트 5030 및 5432가 열려 있는지 확인합니다. 포트 5030은 Windows에 대한 REST 호출을 하는 데 사용됩니다. 포트 5432 포트는 PostgreSQL 연결에 사용됩니다.





NOTE: xCP File Analytics 서버는 항상 Linux 시스템에서 실행됩니다. SMB File Analytics에 대해 별도의 설치를 사용할 수 없습니다. Windows 사용자이고 SMB용 File Analytics 공유를 실행하려면 Linux용 File Analytics를 설치하고 Windows 상자를 Linux 데이터베이스에 연결해야 합니다. xCP File Analytics만 사용하는 경우 NFS용 xCP 카탈로그를 구성할 필요가 없습니다.
