---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: File Analytics for NFS를 설치하거나 업그레이드합니다 
---
= File Analytics for NFS를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
File Analytics for NFS를 설치하거나 업그레이드합니다.

.이 작업에 대해
NFS에 대한 시스템 요구 사항은 를 참조하십시오 link:xcp-install-xcp-nfs.html["xCP NFS를 설치합니다"].

를 클릭합니다 `configure.sh` 스크립트는 RHEL(Red Hat Enterprise Linux) 호스트 시스템에 XCP 파일 분석을 설치합니다. 설치 과정에서 스크립트는 Postgres Database, Apache HTTPD 서버 및 기타 필수 패키지를 호스트 Linux 시스템에 설치합니다. 지원되는 특정 RHEL 버전에 대한 자세한 내용은 를 참조하십시오 link:https://mysupport.netapp.com/matrix/["IMT"^]. 필요에 따라 최신 버전으로 변경하거나 업데이트하고 보안 지침을 준수할 수 있습니다. 에 대해 자세히 알아보십시오 `configure.sh` 스크립트, 를 실행합니다 `./configure.sh -h` 를 클릭합니다.

.시작하기 전에
* XCP 작업이 실행 중인 경우 NetApp 구성을 시작하기 전에 작업을 완료하는 것이 좋습니다.
* Linux 시스템은 Yum 리포지토리 서버 또는 인터넷에 연결되어 있어야 합니다.
* Linux 시스템에 방화벽이 구성되어 있는 경우 방화벽 설정을 변경하여 포트 5030을 활성화해야 합니다. 포트 5030은 XCP 서비스에서 사용됩니다.


.단계
. File Analytics for NFS를 설치하거나 업그레이드합니다.
+
[role="tabbed-block"]
====
.파일 분석을 설치합니다
--
.. 로 이동합니다 `xcp` 폴더를 선택하고 를 실행합니다 `./configure.sh` 스크립트.
+
설치에 성공하면 다음 메시지가 표시됩니다.

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: 이 사용자 이름과 암호를 사용하여 File Analytics GUI에 로그인할 수 있습니다.



--
.파일 분석을 업그레이드합니다
--
.. 로 이동합니다 `xcp` 폴더를 선택하고 실행합니다 `./configure.sh -f`.
.. 프롬프트에서 를 입력합니다 `y` 시스템을 정리하고 재구성합니다.
+
스크립트가 승인되면 기존 구성을 지우고 시스템을 다시 구성합니다.

+
성공하면 다음 메시지가 표시됩니다.

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. 지원되는 브라우저에서 파일 분석을 시작합니다. * \https://<ip 주소 of Linux > /xCP *.
+
을 참조하십시오 link:xcp-install-xcp-nfs.html["xCP NFS를 설치합니다"] 지원되는 브라우저에 대한 자세한 내용은


