---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: SMB용 File Analytics를 설치하거나 업그레이드합니다 
---
= SMB용 File Analytics를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SMB용 File Analytics를 설치하거나 업그레이드합니다.

.이 작업에 대해
SMB의 시스템 요구 사항은 을 참조하십시오 link:xcp-install-xcp-smb.html["xCP SMB를 설치합니다"].

.시작하기 전에
* xCP SMB 서비스를 사용하려면 Linux 시스템에서 NFS용 xCP File Analytics를 구성해야 합니다.
* Windows 시스템에서 xCP File Analytics를 구성하기 전에 Linux 시스템에서 xCP 서비스가 실행되고 있는지 확인하십시오.




== SMB용 File Analytics를 새로 설치합니다

SMB용 File Analytics를 새로 설치하려면 다음 단계를 수행하십시오.

.단계
. 를 복사합니다 `xcp.exe` 파일을 Windows에 저장합니다 `C:` 드라이브, 이 바이너리는 내부에서 사용할 수 있습니다 `/xcp/windows` 의 압축을 푼 후 `tgz` 파일.
. 에서 xCP 라이센스 파일을 다운로드합니다 link:https://xcp.netapp.com/["xCP 사이트"^].
. 'C:\\NetApp\xCP' 폴더를 생성하고 xCP 라이센스를 이 위치에 복사합니다.
. 명령 프롬프트에서 다음 명령을 사용하여 xCP 라이센스를 활성화합니다. "xcp.exe activate"
. Windows CLI 명령 프롬프트에서 'xCP configure'를 실행합니다.
. 메시지가 표시되면 XCP File Analytics 서버가 구성된 Linux 시스템의 IP 주소를 입력합니다.
. 를 복사합니다 `server.key` 및 `server.crt` 에서 파일 `/opt/NetApp/xFiles/xcp/` (XCP File Analytics가 이미 구성되어 있는 Linux 상자에서) `C:\NetApp\XCP`.
+
필요한 경우 CA 인증서가 있는 경우 에 인증서를 배치합니다 `C:\NetApp\XCP` 동일한 이름 및 확장명을 사용합니다.

. Windows 컴퓨터로 이동하여 실행합니다 `xcp listen`이제 SMB용 XCP File Analytics가 구성되었습니다. 서비스를 계속 실행하려면 창을 열어 두십시오.
. 지원되는 브라우저에서 File Analytics 시작: `\https://<ip address of linux>/xcp`
+
을 참조하십시오 link:xcp-install-xcp-smb.html["xCP SMB를 설치합니다"] 지원되는 브라우저에 대한 자세한 내용은

. 를 선택합니다 `OK` 대화 상자가 표시되면
+

NOTE: 새 탭이 열립니다. 팝업이 차단되어 있는 경우 브라우저에서 팝업을 활성화합니다.

. URL의 개인 정보 보호 정책을 수락합니다. 다음 메시지가 표시됩니다. `SMB agent is ready to use. Please refresh the analytics page`
. XCP 파일 분석 GUI를 호스팅하는 원래 탭으로 돌아가 페이지를 새로 고쳐 에이전트 카드 아래에 SMB 에이전트를 표시합니다.




== SMB를 위한 파일 분석 업그레이드

기존 File Analytics for SMB를 업그레이드하려면 다음 단계를 완료하십시오.

. File Analytics를 실행하기 전에 File Analytics가 실행 중인 Linux 서버도 업그레이드되고 서비스가 실행 중인지 확인합니다.
. Windows에서는 명령줄에 CTRL-C를 입력하여 기존 XCP 서비스를 중지합니다.
. 대치 `xcp.exe` 최신 바이너리.
. Windows 컴퓨터로 이동하여 실행합니다 `xcp listen` SMB에 대한 XCP 파일 분석을 구성합니다. 서비스를 계속 실행하려면 창을 열어 두십시오.
. 지원되는 브라우저에서 File Analytics 시작: `\https://<ip address of linux>/xcp`
+
을 참조하십시오 link:xcp-install-xcp-smb.html["xCP SMB를 설치합니다"] 지원되는 브라우저에 대한 자세한 내용은

. 대화 상자가 표시되면 * 확인 * 을 선택합니다.
+

NOTE: 새 탭이 열립니다. 팝업이 차단되어 있는 경우 브라우저에서 팝업을 활성화합니다.

. URL의 개인 정보 보호 정책을 수락합니다. 다음 메시지가 표시됩니다. `SMB agent is ready to use. Please refresh the analytics page`
. XCP 파일 분석 GUI를 호스팅하는 원래 탭으로 돌아가 페이지를 새로 고쳐 에이전트 카드 아래에 SMB 에이전트를 표시합니다.

