---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: POSIX 커넥터를 통해 XCP는 NFSv4, XFS 및 Veritas와 같은 Linux 마운트 파일 시스템에 액세스할 수 있습니다. 
---
= 동일한 xCP 호스트에서 여러 xCP 작업을 실행합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
xCP 1.9.2부터 "-minmem" 기능을 사용하여 각 작업에 충분한 리소스가 호스트에 있는 한 단일 xCP 호스트에서 여러 xCP 작업 또는 명령을 실행할 수 있습니다. "-minmem" 기능을 지원하는 명령을 실행하면 xCP는 최소 호스트 메모리를 사용하여 작업을 완료합니다. 이 작업은 동일한 호스트 구성에서 추가 작업을 실행할 용량을 생성합니다.



== 최소 시스템 요구 사항

각 XCP 작업에 대해 중간 규모에서 대규모 마이그레이션을 위해 최대 64GB의 호스트 메모리와 8개의 코어를 허용해야 합니다.


NOTE: SMB 데이터 마이그레이션에서는 "-minmem" 기능이 지원되지 않습니다.



== 로깅

기본적으로 각 xCP 작업은 작업 ID에 고유한 별도의 로그 파일에 기록됩니다. 이 로깅 메커니즘은 동일한 개별 호스트에서 여러 작업을 실행할 때 잘 작동합니다. NetApp은 를 변경하지 않는 것이 좋습니다 `xcpLogConfig.Json` 파일 - 단일 파일 사용 `xcp.log` 동일한 호스트에서 여러 XCP 작업을 병렬로 로그할 수 있는 파일입니다.



== 지원되는 명령

"-minmem" 기능은 다음 xCP 명령을 통해 지원됩니다.

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== 지원되지 않는 명령입니다

"-minmem" 기능은 에서 지원되지 않습니다 `sync` 명령.



== 명령 예

"-minmem" 기능을 사용하려면 다음 예제와 같이 xCP 명령에 "-minmem" 옵션을 포함해야 합니다.

* `xcp copy -newid _new ID_ *-minmem* src_server:/src_export dst_server:/dst_export`
* `xcp resume [options] -id *-minmem* _copy ID_`
* `xcp verify *-minmem* src_server:/src_export dst_server:/dst_export`


* HDFS 경로 예 *:

* `xcp copy *-minmem* hdfs:///user/demo1/data \file:///user/demo1/dest`
* `xcp verify *-minmem* hdfs:///user/demo1/data \file:///user/demo1/dest`
* `xcp copy -minmem hdfs:///user/demo1/data s3://bucket1`


* POSIX 경로 예 *:

* `xcp copy *-minmem* -newid _new ID_ \file:///mnt/source \file:///mnt/dest`
* `xcp verify *-minmem* \file:///mnt/source \file:///mnt/dest`

