---
sidebar: sidebar 
permalink: xcp-reference-logging-syslog.html 
keywords: netapp, xcp, reference, event, logging 
summary: XCP 로깅 
---
= syslog 클라이언트를 활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP는 syslog 클라이언트를 지원하여 NFS 및 SMB용 원격 syslog 수신기로 XCP 이벤트 로그 메시지를 전송합니다. 기본 포트 514를 사용하여 UDP 프로토콜을 지원합니다.



== NFS 및 SMB에 대해 syslog 클라이언트를 구성합니다

syslog 클라이언트를 활성화하려면 을 구성해야 합니다 `syslog` 옵션을 선택합니다 `xcpLogConfig.json` NFS 및 SMB에 대한 구성 파일

NFS 및 SMB용 syslog 클라이언트에 대한 다음 구성 예:

[listing]
----
{
"syslog":{
"isEnabled":true,
"level":"INFO",
"serverIp":"10.101.101.d",
"port":514
},
"sanitize":false
}
----


== Syslog 옵션

다음 표에는 syslog 하위 옵션 및 설명이 나와 있습니다.

[cols="1,1,1,3"]
|===
| 하위 옵션 | JSON 데이터 유형 | 기본값 | 설명 


| `isEnabled` | 부울 | 거짓 | 이 부울 옵션은 XCP에서 syslog 클라이언트를 활성화합니다. 를 로 설정합니다
false는 syslog 구성을 무시합니다. 


| `level` | 문자열 | 정보 | 이벤트 메시지 심각도 필터 수준입니다. 이벤트 메시징은 심각도가 낮은 5가지 심각도 수준(위험, 오류, 경고, 정보 및 디버그)을 지원합니다 


| `serverIp` | 문자열 | 없음 | 이 옵션은 원격 syslog 서버 IP 주소 또는 호스트 이름을 나열합니다. 


| `port` | 인티거 | 514 | 이 옵션은 원격 syslog 수신기 포트입니다. 이 옵션을 사용하여 다른 포트에 syslog 데이터그램을 허용하도록 syslog 수신기를 구성할 수 있습니다. 기본 UDP 포트는 514입니다. 
|===

IMPORTANT: 를 클릭합니다 `sanitize` "syslog" 구성에서 옵션을 지정하면 안 됩니다. 이 옵션은 전역 범위를 가지며 JSON config 내의 로깅, 이벤트 로그 및 syslog에 공통적으로 사용됩니다. 이 값을 "true"로 설정하면 syslog 서버에 게시된 syslog 메시지에 중요한 정보가 숨겨집니다.



== Syslog 메시지 형식입니다

UDP를 통해 원격 syslog 서버로 전송되는 모든 syslog 메시지는 NFS 및 SMB에 대한 RFC 5424 형식에 따라 포맷됩니다.

다음 표는 XCP에 대한 syslog 메시지에 대해 지원되는 RFC 5424에 따른 심각도 수준을 보여 줍니다.

|===
| 심각도 값 | 심각도 수준 


| 3 | 오류: 오류 상태입니다 


| 4 | 경고: 경고 상태 


| 6 | 정보: 정보 메시지입니다 


| 7 | 디버그: 디버그 수준 메시지 
|===
NFS 및 SMB에 대한 syslog 헤더에서 버전 값은 1이고 XCP에 대한 모든 메시지의 기능 값은 1로 설정됩니다(사용자 수준 메시지).
`<PRI> = syslog facility * 8 + severity value`

.NFS용 syslog 헤더가 있는 XCP 애플리케이션 syslog 메시지 형식:
다음 표에는 NFS용 syslog 헤더가 있는 syslog 메시지 형식의 템플릿과 예가 나와 있습니다.

|===
| 템플릿 | 예 


 a| 
`<PRI><version> <Time stamp> <hostname> xcp_nfs - - - <XCP message>`
 a| 
`<14>1 2020-07-08T06:30:34.341Z netapp xcp_nfs - - - INFO {"Event ID": 14,
"Event Category": "XCP job status", "Event Type": "XCP scan completion",
"Event Source": "netapp", "Description": "XCP scan is completed by scanning 8
items"}`

|===
.NFS에 대한 syslog 헤더가 없는 XCP 애플리케이션 메시지입니다
다음 표에는 NFS에 대한 syslog 헤더가 없는 syslog 메시지 형식의 템플릿과 예가 나와 있습니다.

|===
| 템플릿 | 예 


 a| 
`<message severity level i.e CRITICAL, ERROR, WARNING, INFO, DEBUG> <XCP event log message>`
 a| 
`INFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "netapp", "Description": "XCP scan is completed by scanning 8 items"}`

|===
.SMB용 syslog 헤더를 사용하는 XCP 애플리케이션 syslog 메시지 형식입니다
다음 표에는 SMB용 syslog 헤더가 있는 syslog 메시지 형식의 템플릿과 예가 나와 있습니다.

|===
| 템플릿 | 예 


 a| 
`<PRI><version> <Time stamp> <hostname> xcp_smb - - - <XCP message`
 a| 
`<14>1 2020-07-10T10:37:18.452Z bansala01 xcp_smb - - - INFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "NETAPP-01", "Description": "XCP scan is completed by scanning 17 items"}`

|===
.SMB용 syslog 헤더가 없는 XCP 애플리케이션 메시지
다음 표에는 SMB에 대한 syslog 헤더가 없는 syslog 메시지 형식의 템플릿과 예가 나와 있습니다.

|===
| 템플릿 | 예 


 a| 
`<message severity level i.e CRITICAL, ERROR, WARNING, INFO, DEBUG> <XCP event log message>`
 a| 
`NFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "NETAPP-01", "Description": "XCP scan is completed by scanning 17items"}`

|===