---
sidebar: sidebar 
permalink: xcp-smb-reference-copy.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: 'XCP SMB "copy" 명령 참조' 
---
= 복사
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
를 클릭합니다 `copy` 명령은 전체 소스 디렉토리 구조를 검색하여 대상 SMB 공유로 복사합니다. 를 클릭합니다 `copy` 명령에는 소스 및 대상 경로가 변수로 필요합니다. 스캔되고 복사된 파일, 처리량/속도 및 경과 시간 세부 정보가 5초마다 콘솔에 인쇄됩니다.

[NOTE]
====
* 런타임 로그 파일은 "C:\NetApp\xCP" 아래에 저장됩니다.
* 여기 `copy` 명령은 ACL(액세스 제어 목록) 없이 데이터를 복제합니다.


====
.구문
[source, cli]
----
xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====
다음 표에는 가 나열되어 있습니다 `copy` 매개 변수 및 설명

[cols="2*"]
|===
| 매개 변수 | 설명 


| <<smb_copy_help,copy -h,--help>> | 에 대한 자세한 정보를 표시합니다 `copy` 명령. 


| <<사본 - v>> | 디버그 세부 정보 증가 


| <<smb_copy_parallel,복사-병렬();n  | 동시 프로세스의 수를 지정합니다(기본값: <cpu-count>). 


| <<smb_copy_match,복사-일치();필터();  | 필터와 일치하는 파일 및 디렉토리만 처리합니다(참조) `xcp help - match` 참조). 


| <<smb_copy_exclude,복사-제외();필터();  | 필터에서 파일과 디렉터리만 제외합니다 


| <<copy-preserve-atime 을 선택합니다>> | 소스에서 마지막으로 액세스한 날짜를 복원합니다. 


| <<smb_copy_acl,Copy-acl 을 선택합니다>> | 보안 정보를 복사합니다. 


| <<smb_copy_acl,copy-fallback-user  | 로컬(도메인이 아닌) 소스 컴퓨터 사용자의 권한을 받는 대상 컴퓨터의 Active Directory 사용자 또는 로컬(도메인이 아닌) 사용자를 지정합니다. 예: domain\administrator 


| <<smb_copy_acl,copy-fallback-group  | 로컬(도메인이 아닌) 소스 컴퓨터 그룹의 권한을 받는 대상 컴퓨터의 Active Directory 그룹 또는 로컬(도메인이 아닌) 그룹을 지정합니다. 예: domain\administrators 


| <<smb_copy_root,Copy-root 를 선택합니다>> | 루트 디렉토리의 ACL을 복사합니다. 


| <<smb_copy_aclverify,copy-aclverify {yes, no}>> | Copy-ACL 작업 중에 ACL 확인을 건너뛰거나 포함하는 옵션을 제공합니다. 


| <<소유권 복사>> | 소유권을 복사하지 않습니다. 


| <<smb_copy_bs,복사 - BS n  | 읽기/쓰기 블록 크기(기본값: 1M) 


| <<광고 문구>> | 소스 SMB 공유에서 대상 SMB 공유로 NTFS 대체 데이터 스트림을 복사합니다. 
|===


== copy -h,--help

를 사용합니다 `-h` 및 `–-help` 매개 변수 및 `copy` 명령을 사용하여 에 대한 자세한 정보를 표시합니다 `copy` 명령

.구문
[source, cli]
----
xcp copy –help
----
.예제 보기
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp copy –help

usage: xcp copy [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve- atime] [-acl] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-root] [-noownership] [- aclverify {yes,no}] [-bs <n>] [-ads]
         source target

positional arguments:
   source
   target

optional arguments:
-h, --help            show this help message and exit
-v                    increase debug verbosity
-parallel <n>         number of concurrent processes (default: <cpu-count>)
-match <filter>       only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>     Exclude files and directories that match the filter (see `xcp help - exclude` for details)
-preserve-atime       restore last accessed date on source
-acl                  copy security information
-fallback-user FALLBACK_USER
                      the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                      the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
-loglevel <name>      option to set log level filter (default:INFO)
-root                 copy acl for root directory
-noownership          do not copy ownership
-aclverify {yes,no}   choose whether you need to skip acl verification
-bs <n>               read/write block size for copy (default: 1M)
-ads                  copy NTFS alternate data streams.
----
====


== 사본 - v

를 사용합니다 `-v` 매개 변수 `copy` 자세한 디버그 정보를 제공하는 명령입니다.

.구문
[source, cli]
----
xcp copy -v \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1

failed to set attributes for "d1": (5, 'CreateDirectory', 'Access is denied.')
failed to copy "f1.txt": (5, 'CreateFile', 'Access is denied.')
failed to set attributes for "": (5, 'SetFileAttributesW', 'Access is denied.') error setting timestamps on "": errno (code: 5) Access is denied.
H:\p 4\xcp_latest\xcp_cifs\xcp\ main .py copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1
3 scanned, 0 matched, 0 skipped, 1 copied, 0 (0/s), 3 errors
Total Time : 3s
STATUS : FAILED
----
====


== 복사 - 병렬 <n>

를 사용합니다 `-parallel <n>` 매개 변수 `copy` XCP 동시 프로세스의 수를 더 높거나 더 적게 설정하는 명령입니다. 의 기본값입니다 `-parallel` CPU 수와 같습니다.


NOTE: n의 최대값은 61입니다.

.구문
[source, cli]
----
xcp copy -parallel <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -parallel 7	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -parallel 7 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0errors
Total Time : 2s
STATUS : PASSED
----
====


== <filter>를 복사합니다

를 사용합니다 `-match <filter>` 매개 변수 `copy` 전달된 인수와 일치하는 데이터만 복사하는 명령입니다.

.구문
[source, cli]
----
xcp copy -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 5 matched, 4 copied, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== Copy - <filter>를 제외합니다

를 사용합니다 `-exclude <filter>` 매개 변수 `copy` 제외된 데이터만 복사하는 명령입니다.

.구문
[source, cli]
----
xcp copy -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
다음 예에서는 이름에 "resync" 문자열이 있는 파일 및 디렉터리가 복사에 대해 제외되었습니다.

.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -exclude "'resync' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address or hostname of SMB server>\dest_share


xcp copy -exclude 'resync' in name \\<IP address or hostname of SMB server>\source_share \\\\<IP address or hostname of SMB server>\dest_share
18 scanned, 2 excluded, 0 skipped, 15 copied, 122KiB (50.5KiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy-preserve-atime 을 선택합니다

를 사용합니다 `-preserve-atime` 매개 변수 `copy` XCP가 파일을 읽기 전에 "atime"을 원래 값으로 재설정하는 명령입니다.

.구문
[source, cli]
----
xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy-acl-fallback-user <fallback_user>-fallback-group <fallback_group>입니다

를 사용합니다 `-acl` 매개 변수 `copy` ACL(보안 설명자)의 전송을 활성화하는 명령입니다.

를 사용합니다 `-acl` 매개 변수 `-fallback-user` 및 `-fallback-group` 로컬(도메인이 아닌) 소스 컴퓨터 사용자 또는 그룹의 권한을 받기 위해 대상 컴퓨터 또는 Active Directory에서 사용자 및 그룹을 지정하는 옵션입니다. Active Directory의 일치하지 않는 사용자를 참조하지 않습니다.

.구문
[source, cli]
----
xcp copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----


== copy-aclverify {yes, no}

를 사용합니다 `-aclverify {yes,no}` 매개 변수 `copy` ACL 복사 작업 중에 ACL 확인을 건너뛰거나 포함하는 옵션을 제공하는 명령입니다.

를 사용해야 합니다 `-aclverify {yes,no}` 매개 변수 `copy -acl` 명령. 기본적으로 ACL 복사 작업은 ACL을 확인합니다. 를 설정하는 경우 `-aclverify` 옵션을 로 설정합니다 `no`, ACL 확인 및 를 건너뛸 수 있습니다 `fallback-user` 및 `fallback-group` 옵션이 필요하지 않습니다. 를 설정합니다 `-aclverify` 를 선택합니다 `yes`, 이 필요합니다 `fallback-user` 및 `fallback-group` 옵션을 선택합니다.

.구문
[source, cli]
----
xcp copy -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group"
\\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 15s, 0 acls copied xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (634/s), 0 errors, 11 acls copied
Total Time : 16s
STATUS : PASSED

C:\NetApp\xcp>xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (5.61KiB/s), 0 errors, 11 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== Copy-root 를 선택합니다

를 사용합니다 `-root` 매개 변수 `copy` 루트 디렉토리의 ACL을 복사하는 명령입니다.

.구문
[source, cli]
----
xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 200 (108/s), 0 errors, 6 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== 소유권 복사

를 사용합니다 `-noownership` 매개 변수 `copy` 소스에서 대상으로 소유권을 복사하지 않도록 지정하는 명령입니다. 를 사용해야 합니다 `-noownership` 를 사용하여 `-acl` 옵션 및 필요 `fallback-user` 및 `fallback-group` 필수 매개 변수로

.구문
[source, cli]
----
xcp.exe copy -acl -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 135 copied, 4.26MiB (872KiB/s), 0 errors, 15s, 137 acls copied xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (1.01MiB/s), 0 errors, 567 acls copied
Total Time : 17s
STATUS : PASSED
----
====


== 복사 - BS <n>

를 사용합니다 `-bs <n>` 매개 변수 `copy` 명령을 사용하여 읽기/쓰기 블록 크기를 제공합니다. 기본값은 1M입니다.

.구문
[source, cli]
----
xcp.exe copy -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\Netapp\xcp>xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (6.75MiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== 광고 문구

를 사용합니다 `-ads` 매개 변수 `copy` 소스 SMB 공유에서 대상 SMB 공유로 NTFS 대체 데이터 스트림을 복사하는 명령입니다.

.구문
[source, cli]
----
xcp copy -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.예제 보기
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

6   scanned, 0 matched, 0 skipped, 3 copied, 13 (2.41/s), 0 errors, 5s, 10 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	10s, 11 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	15s, 12 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	20s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	25s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	30s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	35s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	40s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	45s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	2m15s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	3m5s, 13 ads copied
xcp copy -ads \\<source_IP_address>\source_share\src \\<desination_IP_address>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 26 (0.137/s), 0 errors, 14 ads copied
Total Time : 3m9s
STATUS : PASSED
----
====